version: '3.7'

services:
  larabox-5.6:
    image: mattiabasone/larabox:5.6
    build:
      context: '.'
      args:
        - PHP_VERSION=5.6
        - ENV=prod
    ports:
      - "80:80"
  larabox-7.4:
    image: mattiabasone/larabox:7.4
    build:
      context: '.'
      args:
        - PHP_VERSION=7.4
        - ENV=prod
    ports:
      - "80:80"